name: Build CruelKernel for S10e

on:
  push:
  workflow_dispatch:

env:
  TOOLCHAIN: cruel
  INSTALLER: yes

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        model: [ "G970F" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libtinfo5 ccache android-sdk-libsparse-utils unzip curl

      - name: Kernel Configure
        run: |
          ./cruelbuild config \
            model=${{ matrix.model }} \
            name="Cruel-v5.3-G970F" \
            toolchain=$TOOLCHAIN \
            -magisk \
            +nohardening \
            +ttl \
            +wireguard \
            +cifs \
            +sdfat \
            +ntfs \
            +morosound \
            +boeffla_wl_blocker

      - name: Deploy Toolchain
        run: git clone --depth 1 -j $(nproc) --branch $TOOLCHAIN --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain

      - name: Kernel Build
        run: ./cruelbuild :build

      - name: Create CruelKernel images
        run: ./cruelbuild :mkimg

      - name: Create CruelKernel installer
        if: env.INSTALLER == 'yes'
        run: ./cruelbuild :pack

      - name: Avoid Double Zipping in Installer
        if: env.INSTALLER == 'yes'
        run: |
          mkdir -p installer && cd installer
          unzip ../CruelKernel.zip

      - name: Upload Kernel Zip
        if: env.INSTALLER == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: CruelKernel-G970F
          path: installer/*
          if-no-files-found: error

      - name: Upload Kernel Images
        if: env.INSTALLER != 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: CruelKernel-G970F
          path: '*.img'
          if-no-files-found: error

      - name: Upload Kernel Info
        uses: actions/upload-artifact@v4
        with:
          name: ConfigurationInfo-G970F
          path: config.*
          if-no-files-found: error
